export const mockSignals = [
  {
    id: 1,
    headline: "McDonald's slashes combo prices 15%",
    city: "New York",
    state: "NY",
    commodity: "cattle",
    score: 82,
    so_what: "Lower margins, volume recovery → beef demand stabilizes.",
    who_bleeds: "Chili's, Applebee's (lost fast-food edge).",
    who_benefits: "McDonald's suppliers, beef futures.",
    signalStrength: "Short casual dining, Long beef suppliers.",
  },
  {
    id: 2,
    headline: "Vegas hotel occupancy drops as water rationing looms",
    city: "Las Vegas",
    state: "NV",
    commodity: "water",
    score: 88,
    so_what: "Drought + tourism weakness = stress on REITs & CMBS.",
    who_bleeds: "Vegas hotels, municipal bonds.",
    who_benefits: "Phoenix & Reno tourism hubs.",
    signalStrength: "Short Vegas REITs, Long Phoenix tourism equities.",
  },
  {
    id: 3,
    headline: "Brazil beef tariffs hit 50% — US supply gains pricing power",
    city: "São Paulo",
    commodity: "cattle",
    score: 90,
    so_what: "Global protein supply shock → US ranchers gain.",
    who_bleeds: "Brazilian exporters.",
    who_benefits: "US ranchers, Tyson Foods.",
    signalStrength: "Long US cattle futures, Short Brazil meatpackers.",
  },
  {
    id: 4,
    headline: "H-2A visa delays strain Olympic food supply chain",
    city: "Paris",
    commodity: "labor",
    score: 84,
    so_what: "Paris Olympics food vendors short on migrant staff.",
    who_bleeds: "Hospitality chains, Olympic sponsors.",
    who_benefits: "Local French suppliers.",
    signalStrength: "Short global hospitality, Long French grocers.",
  },
  {
    id: 5,
    headline: "Walmart faces supply shortages in perishables",
    city: "Bentonville",
    state: "AR",
    commodity: "retail",
    score: 80,
    so_what: "Strain on US retail → consumers shift to Aldi/Costco.",
    who_bleeds: "Walmart equity, US consumers.",
    who_benefits: "Competing discount chains, exporters.",
    signalStrength: "Short Walmart, Long Costco/Aldi suppliers.",
  },
]
